-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 22:39:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mns
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mns
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mns` DEFAULT CHARACTER SET utf8 ;
USE `mns` ;

-- -----------------------------------------------------
-- Table `mns`.`Price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`Price` ;

CREATE TABLE IF NOT EXISTS `mns`.`Price` (
  `Price_ID` INT NOT NULL AUTO_INCREMENT,
  `Guest` DOUBLE NULL,
  `Man` DOUBLE NULL,
  `Woman` DOUBLE NULL,
  PRIMARY KEY (`Price_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mns`.`Localization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`Localization` ;

CREATE TABLE IF NOT EXISTS `mns`.`Localization` (
  `Localization_ID` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(45) NULL,
  `District` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  PRIMARY KEY (`Localization_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mns`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`Place` ;

CREATE TABLE IF NOT EXISTS `mns`.`Place` (
  `Place_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(200) NULL,
  `Rating` DOUBLE NULL,
  `Description` VARCHAR(45) NULL,
  `Path_Galery` VARCHAR(45) NULL,
  `Visible_Flag` TINYINT NULL,
  `Contacts` VARCHAR(15) NULL,
  `Schedule` VARCHAR(45) NULL,
  `GPS` VARCHAR(45) NULL,
  `Localization_ID` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `URL` VARCHAR(45) NULL,
  PRIMARY KEY (`Place_ID`),
  INDEX `fk_Place_Localization1_idx` (`Localization_ID` ASC),
  CONSTRAINT `fk_Place_Localization1`
    FOREIGN KEY (`Localization_ID`)
    REFERENCES `mns`.`Localization` (`Localization_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mns`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`Event` ;

CREATE TABLE IF NOT EXISTS `mns`.`Event` (
  `Event_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Date` DATE NULL,
  `Description` VARCHAR(200) NULL,
  `Visualizations` BIGINT(10) NULL,
  `Path_Flyer` VARCHAR(45) NULL,
  `Price_ID` INT NOT NULL,
  `Place_ID` INT NOT NULL,
  PRIMARY KEY (`Event_ID`),
  INDEX `fk_Event_Price1_idx` (`Price_ID` ASC),
  INDEX `fk_Event_Place1_idx` (`Place_ID` ASC),
  CONSTRAINT `fk_Event_Price1`
    FOREIGN KEY (`Price_ID`)
    REFERENCES `mns`.`Price` (`Price_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Place1`
    FOREIGN KEY (`Place_ID`)
    REFERENCES `mns`.`Place` (`Place_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mns`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`User` ;

CREATE TABLE IF NOT EXISTS `mns`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Gender` CHAR(1) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(45) NULL,
  `Type` CHAR(1) NULL,
  `Username` VARCHAR(15) NULL,
  `Password` CHAR(128) NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mns`.`Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mns`.`Guest` ;

CREATE TABLE IF NOT EXISTS `mns`.`Guest` (
  `User_ID` INT NOT NULL,
  `Event_ID` INT NOT NULL,
  INDEX `fk_Guest_User1_idx` (`User_ID` ASC),
  INDEX `fk_Guest_Event1_idx` (`Event_ID` ASC),
  PRIMARY KEY (`User_ID`, `Event_ID`),
  CONSTRAINT `fk_Guest_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mns`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guest_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `mns`.`Event` (`Event_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
